logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  port: 80
 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/node?useUnicode=yes&characterEncoding=UTF-8&serverTimezon=UTC
    username: root
  devtools:
    livereload:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        ddl-auto: update
  thymeleaf:
    cache: false
